# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pyrattler-recipe-autogen
  version: ${{ env.get("HATCH_VERSION", default="0.0.0+local") }}
  #version: '0.10.3'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ..
  # url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyrattler_recipe_autogen-${{ version }}.tar.gz
  # sha256: 0555b815454b329cbd0efbb545426461f65581af9a056082127f576662e0f126

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation
  python:
    entry_points:
      - pyrattler-recipe-autogen = pyrattler_recipe_autogen.cli:main

requirements:
  host:
  - python 3.9.*
  - pip
  - python-build
  - hatchling
  - hatch-vcs
  run:
  - python >=3.9,<4
  - pyyaml
  - toml
  - if: python <3.11
    then:
      - tomli
      - types-toml
      - types-PyYAML

tests:
  - python:
      imports:
        - pyrattler_recipe_autogen
      pip_check: true
      python_version: 3.9.*
  - requirements:
      run:
        - python 3.9.*
        - toml
    script:
      - pyrattler-recipe-autogen --help

about:
  summary: Generate Rattler-Build recipe.yaml from pyproject.toml
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/millsks/pyrattler-recipe-autogen
  documentation: https://github.com/millsks/pyrattler-recipe-autogen.git#README
  repository: https://github.com/millsks/pyrattler-recipe-autogen.git

extra:
  recipe-maintainers:
    - millsks
