name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (private disclosure)
title: "[Security]: "
labels: ["security", "triage"]
assignees: ["millsks"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report

        **Please do not publicly disclose security vulnerabilities.**

        If you believe you have found a security vulnerability in pyrattler-recipe-autogen, please report it privately through GitHub's Security Advisories feature instead of creating a public issue.

        📧 **Private Reporting Options:**
        1. Use [GitHub Security Advisories](https://github.com/millsks/pyrattler-recipe-autogen/security/advisories/new) (preferred)
        2. Email: millsks@gmail.com with "SECURITY" in the subject line

        This form is for **confirmed** security issues that require immediate public attention or have already been disclosed.

  - type: checkboxes
    id: disclosure-type
    attributes:
      label: Disclosure Type
      description: Please indicate the nature of this security report
      options:
        - label: This is a **confirmed** security vulnerability that requires immediate public attention
          required: false
        - label: This vulnerability has already been **publicly disclosed** elsewhere
          required: false
        - label: I have **already reported** this privately and received permission to create this public issue
          required: false
        - label: This is **NOT** a security vulnerability (consider using bug report template instead)
          required: false
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Security Severity
      description: How severe is this security vulnerability?
      options:
        - Critical - Remote code execution, privilege escalation
        - High - Data exposure, authentication bypass
        - Medium - Denial of service, information disclosure
        - Low - Minor security concern
        - Unknown - Needs assessment
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear and detailed description of the security vulnerability
      placeholder: |
        Describe the security issue, including:
        - What type of vulnerability this is
        - What systems/components are affected
        - What an attacker could potentially do
    validations:
      required: true

  - type: textarea
    id: attack-vector
    attributes:
      label: Attack Vector
      description: How can this vulnerability be exploited?
      placeholder: |
        Describe how an attacker could exploit this vulnerability:
        - Prerequisites (authentication, access level, etc.)
        - Steps to exploit
        - Network/local access requirements
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        Describe the potential impact:
        - What data could be compromised
        - What systems could be affected
        - Business impact
        - User impact
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: Provide a proof of concept or steps to reproduce
      placeholder: |
        Please provide:
        - Step-by-step reproduction instructions
        - Sample code or commands (if applicable)
        - Screenshots or logs (if helpful)

        **Warning: Do not include working exploits that could be used maliciously**
      render: shell
    validations:
      required: true

  - type: dropdown
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this vulnerability?
      multiple: true
      options:
        - Latest version (main branch)
        - v0.1.x series
        - All versions
        - Unknown - needs investigation
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide details about the environment where this vulnerability exists
      placeholder: |
        - Operating System:
        - Python version:
        - pyrattler-recipe-autogen version:
        - Installation method:
        - Other relevant dependencies:
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this vulnerability?
      placeholder: |
        If you have ideas for how to fix this vulnerability:
        - Suggested code changes
        - Alternative approaches
        - Workarounds users can implement
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide any relevant references or related vulnerabilities
      placeholder: |
        - CVE numbers (if applicable)
        - Related security advisories
        - Research papers or blog posts
        - Similar vulnerabilities in other projects
    validations:
      required: false

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I understand the importance of responsible disclosure for security vulnerabilities
          required: true
        - label: I will not publicly share detailed exploitation information until a fix is available
          required: true
        - label: I am willing to work with the maintainers to resolve this issue
          required: true

  - type: textarea
    id: contact-info
    attributes:
      label: Contact Information (Optional)
      description: How can we reach you for follow-up questions?
      placeholder: |
        - GitHub username: (your username)
        - Email: (if you want to be contacted directly)
        - Preferred contact method:

        Note: This information will be visible in the public issue
    validations:
      required: false
