name: Stale Issues and PRs

on:
  schedule:
    # Run daily at 1 AM UTC
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Issues configuration
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs within 7 days.

            If this issue is still relevant, please:
            - Add a comment to keep it open
            - Remove the 'stale' label
            - Provide additional context or updates

            Thank you for your contributions! 🙏
          close-issue-message: |
            This issue has been automatically closed due to inactivity.

            If you believe this issue is still relevant, please feel free to reopen it
            or create a new issue with updated information.
          days-before-issue-stale: 60
          days-before-issue-close: 7
          stale-issue-label: "stale"
          exempt-issue-labels: "pinned,security,bug,enhancement,good first issue"

          # Pull Requests configuration
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs within 14 days.

            If this PR is still relevant, please:
            - Rebase on the latest main branch
            - Address any review feedback
            - Add a comment to keep it open
            - Remove the 'stale' label

            Thank you for your contribution! 🙏
          close-pr-message: |
            This pull request has been automatically closed due to inactivity.

            If you would like to continue working on this, please feel free to reopen
            or create a fresh pull request.
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: "stale"
          exempt-pr-labels: "pinned,security,dependencies,automated"

          # General configuration
          operations-per-run: 100
          remove-stale-when-updated: true
          ascending: true
